Invoice/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Invoice.Core.Entity;
using Invoice.Core.Interfaces;
using Invoice.Core.ViewModel;
using Invoice.Data.Reports;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.PlatformAbstractions;

namespace Invoice.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly ICustomerRepository customerRepository;
        private readonly IProductRepository _productRepository;
        private readonly IStoreSettingRepository storeSettingRepository;
        private readonly ISaleRepository saleRepository;

        public AdminController(ICustomerRepository customerRepository,
            IProductRepository productRepository, IStoreSettingRepository storeSettingRepository,
            ISaleRepository saleRepository)
        {

            this.customerRepository = customerRepository;
            _productRepository = productRepository;
            this.storeSettingRepository = storeSettingRepository;
            this.saleRepository = saleRepository;
        }
        public IActionResult Index()
        {
            var dashboard= new DashboardViewModel
            {
                Customers = customerRepository.All().Count(),
                Products = _productRepository.All().Count(),
                TotalSales = saleRepository.All().Count(),
                TotalSaleValue = saleRepository.All().Sum(x => x.GrandTotal),
                LastFiveSales = saleRepository.All().OrderByDescending(x => x.SalesDate).Take(5).ToList()
            };
            return View(dashboard);
        }


        #region customer
        public IActionResult CustomerList()
        {
            return View(customerRepository.All());
        }

        [HttpGet]
        public ActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCustomer(CustomerModel model)
        {
            if (ModelState.IsValid)
            {
                customerRepository.Insert(model);
                return RedirectToAction("CustomerList");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult EditCustomer(int customerId)
        {
            var customer = customerRepository.Find(customerId);
            return View(customer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCustomer(CustomerModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            customerRepository.Update(model, model.Id);
            return RedirectToAction("CustomerList");
        }

        public ActionResult DeleteCustomer(int customerId)
        {
            var customer = customerRepository.Find(customerId);
            if (customer != null)
            {
                customerRepository.Delete(customer);
                return RedirectToAction("CustomerList");
            }
            return RedirectToAction("CustomerList");
        }
        #endregion

        #region Product
        public IActionResult ProductList()
        {
            var products = _productRepository.All();
            return View(products);
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProduct(ProductModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _productRepository.Insert(model);
            return RedirectToAction("ProductList");
        }
        [HttpGet]
        public IActionResult EditProduct(int productId)
        {
            var product = _productRepository.Find(productId);
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProduct(ProductModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _productRepository.Update(model, model.Id);
            return RedirectToAction("ProductList");
        }
        public ActionResult DeleteProduct(int productId)
        {
            var product = _productRepository.Find(productId);
            if (product != null)
            {
                _productRepository.Delete(product);
                return RedirectToAction("ProductList");
            }
            return RedirectToAction("ProductList");
        }


        [HttpGet]
        public ActionResult BarcodeGenerate()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BarcodeGenerate(int productId, int quantity)
        {
            //{
            //    Document doc = new Document(new iTextSharp.text.Rectangle(24, 12), 5, 5, 1, 1);
            //    try
            //    {

            //        PdfWriter writer = PdfWriter.GetInstance(doc, new FileStream(
            //          Environment.GetFolderPath(Environment.SpecialFolder.Desktop) + "/codes.pdf", FileMode.Create));
            //        doc.Open();

            //        DataTable dt = new DataTable();
            //        dt.Columns.Add("ID");
            //        dt.Columns.Add("Price");
            //        for (int i = 0; i < 20; i++)
            //        {
            //            DataRow row = dt.NewRow();
            //            row["ID"] = "ZS00000000000000" + i.ToString();
            //            row["Price"] = "100," + i.ToString();
            //            dt.Rows.Add(row);
            //        }
            //        System.Drawing.Image img1 = null;
            //        for (int i = 0; i < dt.Rows.Count; i++)
            //        {
            //            if (i != 0)
            //                doc.NewPage();
            //            PdfContentByte cb1 = writer.DirectContent;
            //            BaseFont bf = BaseFont.CreateFont(BaseFont.TIMES_BOLDITALIC, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);

            //            cb1.SetFontAndSize(bf, 2.0f);
            //            cb1.BeginText();
            //            cb1.SetTextMatrix(1.2f, 9.5f);
            //            cb1.ShowText("Safi Garments");
            //            cb1.EndText();

            //            PdfContentByte cb2 = writer.DirectContent;
            //            BaseFont bf1 = BaseFont.CreateFont(BaseFont.HELVETICA, BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
            //            cb2.SetFontAndSize(bf1, 1.3f);
            //            cb2.BeginText();
            //            cb2.SetTextMatrix(17.5f, 1.0f);
            //            cb2.ShowText(dt.Rows[i]["Price"].ToString());
            //            cb2.EndText();

            //            iTextSharp.text.pdf.PdfContentByte cb = writer.DirectContent;
            //            iTextSharp.text.pdf.Barcode128 bc = new Barcode128();
            //            bc.TextAlignment = Element.ALIGN_LEFT;
            //            bc.Code = dt.Rows[i]["ID"].ToString();
            //            bc.StartStopText = false;
            //            bc.CodeType = iTextSharp.text.pdf.Barcode128.EAN13;
            //            bc.Extended = true;

            //            //System.Drawing.Image bimg = 
            //            //  bc.CreateDrawingImage(System.Drawing.Color.Black, System.Drawing.Color.White);
            //            //img1 = bimg;

            //            iTextSharp.text.Image img = bc.CreateImageWithBarcode(cb,
            //              iTextSharp.text.BaseColor.BLACK, iTextSharp.text.BaseColor.BLACK);

            //            cb.SetTextMatrix(1.5f, 3.0f);
            //            img.ScaleToFit(60, 5);
            //            img.SetAbsolutePosition(1.5f, 1);
            //            cb.AddImage(img);
            //        }
            //    }
            //    catch
            //    {
            //    }
            //    finally
            //    {
            //        doc.Close();
            //    }

            if (ModelState.IsValid)
            {
                ProductReport paymentReport = new ProductReport();
                byte[] bytes = paymentReport.CreateReport();
                return File(bytes, "application/pdf");
            }
            return RedirectToAction("BarcodeGenerate");
        }
        #endregion

        #region Sales
        public IActionResult SalesList()
        {
            return View();
        }
        #endregion

        #region store
        [HttpGet]
        public IActionResult Settings()
        {
            var settings = storeSettingRepository.All().FirstOrDefault();
            if (settings != null)
                return View(settings);
            return View(new StoreSettingModel());
        }
        [HttpPost]


        public IActionResult Settings(StoreSettingModel model, IFormFile logoPostedFileBase)
        {
            if (!ModelState.IsValid) return View(model);
            if (logoPostedFileBase != null && logoPostedFileBase.Length > 0)
            {
                var path = Path.Combine(
                 Directory.GetCurrentDirectory(), "wwwroot/Images",
                 logoPostedFileBase.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    logoPostedFileBase.CopyTo(stream);
                }
                model.Logo = $"/Images/{logoPostedFileBase.FileName}";
            }
            else
            {
                var settings = storeSettingRepository.Find(model.Id);
                if (settings != null)
                    model.Logo = settings.Logo;
            }

Invoice/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Invoice.Core.Entity;
using Invoice.Core.Interfaces;
using Invoice.Core.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PharmaApp.Web.Reports;

namespace Invoice.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private readonly ICustomerRepository customerRepository;
        private readonly ISaleRepository saleRepository;
        private readonly ISaleItemRepository saleItemRepository;
        private readonly IStoreSettingRepository storeSettingRepository;
        private readonly IConfiguration configuration;

        public SalesController(ICustomerRepository customerRepository, ISaleRepository saleRepository,
            ISaleItemRepository saleItemRepository, IStoreSettingRepository storeSettingRepository, IConfiguration configuration)
        {
            this.configuration = configuration;
            this.customerRepository = customerRepository;
            this.saleRepository = saleRepository;
            this.saleItemRepository = saleItemRepository;
            this.storeSettingRepository = storeSettingRepository;
           
        }

        public IActionResult Index()
        {
            return View(saleRepository.All());
        }
        [HttpGet]
        public IActionResult AddSale()
        {
            ViewBag.customers = customerRepository.GetAllForDropDown();
            return View();
        }
        [HttpPost]
        public IActionResult AddSale([FromBody] SalesModel model)
        {
            if (ModelState.IsValid)
            {
                saleRepository.Insert(model);
                return Json(new { error = false, message = "Sales saved successfully" });
            }
            return Json(new { error = true, message = "failed to save Sales" });
        }
        [HttpGet]
        public IActionResult EditSale(int saleId)
        {
            return View(model: saleId);
        }
        [HttpPost]
        public IActionResult EditSale(SalesModel model)
        {
            if (model != null)
            {
                var items = saleItemRepository.All().Where(x => x.SalesId == model.Id).ToList();
                if (items.Any())
                {
                    foreach (var item in items)
                    {
                        saleItemRepository.Delete(item);
                    }
                }

                var sale = saleRepository.Find(model.Id);
                sale.Notes = model.Notes;
                sale.PaymentMethod = model.PaymentMethod;
                sale.SaleCode = model.SaleCode;
                sale.CustomerId = model.CustomerId;
                sale.Total = model.Total;
                sale.SalesDate = model.SalesDate;
                sale.Status = model.Status;
                sale.Discount = model.Discount;
                sale.GrandTotal = model.GrandTotal;

                //add again
                foreach (var item in model.Items)
                {
                    sale.Items.Add(new SalesItemsModel
                    {
                        Price = item.Price,
                        Amount = item.Amount,
                        Quantity = item.Quantity,
                        Name = item.Name
                    });
                }
                saleRepository.Update(sale, model.Id);
                return Json(new { error = false, message = "Sales updated successfully" });
            }
            return Json(new { error = true, message = "failed to update Sales" });
        }

        public IActionResult DeleteSale(int saleId)
        {
            var item = this.saleRepository.Find(saleId);
            saleRepository.Delete(item);
            return RedirectToAction("index");
        }
        [HttpGet]
        public ActionResult SalesReport(DateTime? From, DateTime? To)
        {
            if (From.HasValue && To.HasValue)
                return View(saleRepository.All().Where(x => x.SalesDate >= From && x.SalesDate <= To));
            return View(new List<SalesModel>());
        }

        public ActionResult SaleInvoice(int saleId, int style)
        {
            if (storeSettingRepository.All().Count() == 0)
            {
                TempData["Msg"] = "Setup store setting first then print sale invoice";
                return RedirectToAction("Index");
            }
            var store = storeSettingRepository.All().FirstOrDefault();

            var sale = saleRepository.All().Include(x => x.CustomerModel).SingleOrDefault(x => x.Id == saleId);
            sale.Items = saleItemRepository.All().Where(x => x.SalesId == saleId).ToList();
            if (sale != null)
            {
                var sales = new SaleReportViewModel
                {
                    company = store,
                    Sales = sale
                };
                if (style == 1)
                {
                    SalesReport paymentReport = new SalesReport(configuration);
                    byte[] bytes = paymentReport.CreateReport(sales);
                    return File(bytes, "application/pdf");
                }
                if (style == 2)
                {
                    SalesReportSmall paymentReport = new SalesReportSmall();
                    byte[] bytes = paymentReport.CreateReport(sales);
                    return File(bytes, "application/pdf");
                }
            }
            return RedirectToAction("index");
        }
        [HttpGet]
        public JsonResult GetSales(int saleId)
        {
            try
            {
                SalesModel sales = saleRepository.All().FirstOrDefault(x => x.Id == saleId);
                sales.Items = saleItemRepository.All().Where(x => x.SalesId == sales.Id).ToList();
                //SalesItemsModel a = new SalesItemsModel { Name = "abc", Amount = 2.5, Id = 1, IsDelete = false, Price = 2.5, Quantity = 1, SalesId = 5};
                //sales.Items.Add(a);
                return Json(sales);
            }
            catch (Exception e){
                return Json(e.ToString());
            }
           
        }

        public JsonResult GetCustomers()
        {
            return Json(customerRepository.All());
        }
    }
}

Invoice/Views/Admin/CustomerList.cshtml
@model IEnumerable<Invoice.Core.Entity.CustomerModel>
@{
    ViewData["Title"] = "Customer List";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}



<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Customer List</h4>
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover  table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Email</th>
                                        <th>Phone</th>
                                        <th>Notes</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>@item.Email</td>
                                            <td>@item.Phone</td>
                                            <td>@item.Notes</td>
                                            <td>
                                                <a href="@Url.Action("EditCustomer", "Admin", new {customerId = item.Id})" class="btn btn-icon btn-warning btn-xs m-b-5">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a href="@Url.Action("DeleteCustomer", "Admin", new {customerId = item.Id})" onclick="return confirm('Are you sure you want to Remove this customer?')" class="btn btn-icon btn-danger btn-xs m-b-5">
                                                    <i class="fa fa-remove"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>





@section scripts{
    
}

Invoice/Views/Admin/EditCustomer.cshtml
@model Invoice.Core.Entity.CustomerModel
@{
    ViewData["Title"] = "Edit Customer";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}


<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Edit Customer</h4>
                    </div>
                    <div class="card-body">
                        <div class="basic-elements">
                            <form asp-controller="Admin" asp-action="EditCustomer" method="post">
                                <input asp-for="Id" type="hidden" />
                                <div class="row">
                                    <div class="col-lg-8">
                                        <div class="form-group">
                                            <label asp-for="Name"></label>
                                            <input type="text" asp-for="Name" class="form-control" placeholder="eg Elon Mask">
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Email"></label>
                                            <input asp-for="Email" class="form-control" type="email" placeholder="Enter Email">
                                            <span asp-validation-for="Email" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Phone"></label>
                                            <input asp-for="Phone" class="form-control" type="text" placeholder="Enter phone">
                                            <span asp-validation-for="Phone" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Address"></label>
                                            <textarea class="form-control" asp-for="Address" rows="4" placeholder="Text input"></textarea>
                                            <span asp-validation-for="Address" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <label asp-for="Notes"></label>
                                            <input asp-for="Notes" class="form-control" type="tel" placeholder="Enter Notes">
                                            <span asp-validation-for="Notes" class="text-danger"></span>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-success"> Update Changes </button>
                                        </div>

                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>

Invoice/Views/Admin/Index.cshtml
@model Invoice.Core.ViewModel.DashboardViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
    int i = 1;
}

<div class="page-wrapper">
    <!-- Bread crumb -->
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-primary">Dashboard</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
            </ol>
        </div>
    </div>
    <!-- End Bread crumb -->
    <!-- Container fluid  -->
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-md-3">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-usd f-s-40 color-primary"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>@Model.TotalSaleValue</h2>
                            <p class="m-b-0">Total Revenue</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-shopping-cart f-s-40 color-success"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>@Model.TotalSales</h2>
                            <p class="m-b-0">Total Sales</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-archive f-s-40 color-warning"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>@Model.Products</h2>
                            <p class="m-b-0">Total Products</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-user f-s-40 color-danger"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>@Model.Customers</h2>
                            <p class="m-b-0">Customer</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-title">
                        <h4>Five Recent Sales </h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Code</th>
                                        <th>Date</th>
                                        <th>Grand Total</th>
                                        <th>Status</th>
                                        <th> Print</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.LastFiveSales)
                                    {
                                        <tr>
                                            <td>@i</td>
                                            <td>@item.SaleCode</td>
                                            <td>@(String.Format("{0:dd/MM/yyyy}", item.SalesDate))</td>
                                            <td>@item.GrandTotal</td>
                                            <td>
                                                @if (item.Status == "Due")
                                                {
                                                    <label class="label label-warning">due</label>

                                                }
                                                @if (item.Status == "Paid")
                                                {
                                                    <label class="label label-success">paid</label>

                                                }
                                            </td>
                                            <td>
                                                <a href="@Url.Action("SaleInvoice","Sales", new {saleId = item.Id,style=1})" title="Invoice 1" class="btn btn-icon btn-primary btn-xs m-b-5"><i class="fa fa-print"> </i> </a>

                                                <a href="@Url.Action("SaleInvoice","Sales", new {saleId = item.Id,style=2})" title="Invoice 2" class="btn btn-icon btn-primary btn-xs m-b-5"><i class="fa fa-print"> </i> </a>
                                            </td>
                                        </tr>
                                        i++;
                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Invoice/Views/Admin/ProductList.cshtml
@model  IEnumerable<Invoice.Core.Entity.ProductModel>
@{
    ViewData["Title"] = "Product List";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<div class="page-wrapper">
    <div class="container-fluid">
        <!-- Start Page Content -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Product List</h4>
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover  table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Code</th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Code</td>
                                            <td>@item.Name</td>
                                            <td>@item.Price</td>
                                           
                                            <td>
                                                <a href="@Url.Action("EditProduct", "Admin", new {productId = item.Id})" class="btn btn-icon btn-warning btn-xs m-b-5">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a href="@Url.Action("DeleteProduct", "Admin", new {productId = item.Id})" onclick="return confirm('Are you sure you want to Remove this product?')" class="btn btn-icon btn-danger btn-xs m-b-5">
                                                    <i class="fa fa-remove"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End PAge Content -->
    </div>
</div>





@section scripts{
    
}

Invoice/Views/Admin/SalesList.cshtml
@{
    ViewData["Title"] = "SalesList";
    Layout = "~/Views/Shared/_adminLayout.cshtml";
}

<h2>SalesList</h2>